name: Use debian ros packages in Ubuntu 22.04 along with source packages

on:
  push:
  workflow_dispatch:

jobs:
  ubuntu2204:
    runs-on: ubuntu-22.04
    env:
      DEST: $HOME/other/install
    steps:
      - name: git clone ros_from_src
        uses: actions/checkout@v3
        with:
          path: other/src/ros_from_src

      - name: apt installs
        run: |
          sudo apt install -yqq git
          sudo apt install -yqq ros-*
          sudo apt install -yqq catkin-lint cython3 libapriltag-dev libceres-dev libfrei0r-ocaml-dev
          sudo apt install -yqq libgeographic-dev libgmock-dev libgoogle-glog-dev libgst-dev
          sudo apt install -yqq libgstreamer-plugins-base1.0-dev libgstreamer1.0-dev
          sudo apt install -yqq libimage-view-dev liborocos-bfl-dev libpcl-ros-dev libqt5svg5-dev libqt5websockets5-dev
          sudo apt install -yqq libqt5x11extras5-dev libqwt-qt5-dev libsdl-image1.2-dev
          sudo apt install -yqq libspnav-dev liburdfdom-dev libuvc-dev libv4l-dev libyaml-cpp-dev
          sudo apt install -yqq python-is-python3 python3-tf2-geometry-msgs python3-venv vim curl jq

      - name: setup
        run:
          mkdir -p other/src
          echo "$DEST/bin" >> $GITHUB_PATH

      - name: vcs
        run: |
          cd other/src
          git clone git@github.com:dirk-thomas/vcstool.git
          cd vcstool
          python3 setup.py install --prefix=$DEST --record install_manifest.txt --single-version-externally-managed
          vcs --help

      - name: pycommon
        run: |
          cd other/src
          git clone git@github.com:osrf/osrf_pycommon
          cd osrf_pycommon
          python3 setup.py install --prefix=$DEST --record install_manifest.txt --single-version-externally-managed

      - name: setup base_catkin_ws
        run: |
          mkdir -p base_catkin_ws/src
          cd ~/base_catkin_ws/src
          ln -s other/src/ros_from_src/ubuntu_2204/base_repos.yaml
          vcs import --shallow < base_repos.yaml
          # ignore repos that aren't yet building in 22.04
          other/src/ros_from_src/ubuntu_2204/ignore.sh

      - name: build base_catkin_ws
        run: |
          cd base_catkin_ws
          catkin config --cmake-args -DCMAKE_BUILD_TYPE=Release -Wno-deprecated
          catkin build
          source devel/setup.bash
