name: Noetic ROS build from source

on:
  push:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-20.04
    # env:
    steps:
      - name: git clone git@github.com:lucasw/ros_from_src
        uses: actions/checkout@v2
        with:
          path: ros_from_src
          submodules: recursive

      - name: local build
        run: |
          mkdir staging
          cd staging
          sudo ../ros_from_src/dependencies.sh
          ../ros_from_src/git_clone.sh
          ../ros_from_src/build.sh

      - name: docker build 20.04
        run: |
          cd ros_from_src
          docker build --build-arg IMAGE=ubuntu:20.04 --build-arg PYTHON_MINOR_VERSION=8 . -t ros2004

      - name: docker build 22.04
        run: |
          cd ros_from_src
          docker build --build-arg IMAGE=ubuntu:22.04 --build-arg PYTHON_MINOR_VERSION=9 . -t ros2204

      # - name: deps
      #   run: |
      #     sudo apt install -y python3-nose
      #     sudo apt install -y googletest
      #     # sudo apt install -y python-catkin-pkg
      #     sudo apt install -y python3-empy
      #     sudo apt install -y google-mock
      # - name: Catkin
      #   run: |
      #     ls -l
      #     mkdir build/catkin -p
      #     cd build/catkin
      #     cmake ../../ros/core/catkin -DCATKIN_BUILD_BINARY_PACKAGE=OFF -DCMAKE_INSTALL_PREFIX=/opt/ros/noetic -DPYTHON_EXECUTABLE=/usr/bin/python -DSETUPTOOLS_DEB_LAYOUT=OFF
      #     make
      #     make install
      #     ls -l /opt/ros/noetic
